server:
  port: 80

spring:
  datasource:
    url: "jdbc:mysql://127.0.0.1:3306/test-api?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC"
    username: root
    password: asxc2684!@
    driver-class-name: com.mysql.cj.jdbc.Driver

jwt:
  secret: 482B4D6251655468576D5A7134743777217A25432646294A404E635266556A58