server:
  port: 80

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/test-api?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC"
    username: ENC(BY3yvBp8ooLt8y/rcj4A9g==)
    password: ENC(O+f2ALd1DSW01lK9cdoPFCNNIAAVuU/D)
    driver-class-name: com.mysql.cj.jdbc.Driver

jwt:
  secret: 482B4D6251655468576D5A7134743777217A25432646294A404E635266556A58

jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    algorithm: PBEWithMD5AndDES
    pool-size: 2
    string-output-type: base64
    key-obtention-iterations: 100000
    password: password