server:
  port: 80

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/test-api?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC"
    username: ENC(xSevd3fW1RQzoYfXvnriXg==)
    password: ENC(xR7+cwI+/zj6h6HwINjdm5xJxbndY5l5)
    driver-class-name: com.mysql.cj.jdbc.Driver

jwt:
  secret: 482B4D6251655468576D5A7134743777217A25432646294A404E635266556A58

jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    password : 1234